name: Deploy Functions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ENV_FILE: ${{ secrets.SUPABASE_ENV_FILE }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 'Create Supabase env file'
        run: |
          echo "${{ secrets.SUPABASE_ENV_FILE }}" > .env
      
      - name: 'Create link to Supabase project'
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID --password ""
      
      - name: 'Set Supabase .env file'
        run: |
          supabase secrets set --env-file .env
      
      - name: 'Deploy Sera on Supabase'
        run: |
          supabase functions deploy sera --project-ref $SUPABASE_PROJECT_ID
                
      - name: 'Deploy Chat-lines on Supabase'
      run: |
        supabase functions deploy chat-lines --project-ref $SUPABASE_PROJECT_ID
