name: Functions Workflow

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1.1.1
        with:
          deno-version: v1.x # Run with latest stable Deno.

      # Scan the code for syntax errors and style issues. If
      # you want to use a custom linter configuration you can add a configuration file with --config <myconfig>
      - run: deno lint

      # Run all test files in the repository and collect code coverage. The example
      # runs with all permissions, but it is recommended to run with the minimal permissions your program needs (for example --allow-read).
      - run: deno test --import-map=./supabase/functions/import_map.json

  deploy:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    needs: lint-and-test

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      SUPABASE_ENV_FILE: ${{ secrets.SUPABASE_ENV_FILE }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: 'Create Supabase env file'
        run: |
          echo "${{ secrets.SUPABASE_ENV_FILE }}" > .env
      
      - name: 'Create link to Supabase project'
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_ID --password ""
      
      - name: 'Set Supabase .env file'
        run: |
          supabase secrets set --env-file .env
      
      - name: 'Deploy Sera on Supabase'
        run: |
          supabase functions deploy sera --project-ref $SUPABASE_PROJECT_ID
